package cz.ucl.logic.app.entities;

import cz.ucl.logic.app.entities.definition.Color;
import cz.ucl.logic.app.entities.definition.ICategory;
import cz.ucl.logic.app.entities.definition.ITask;
import cz.ucl.logic.app.entities.definition.IUser;

import javax.persistence.Entity;

@Entity
public final class Category extends TaskOwner implements ICategory {

    private final int id;
    private final String title;

    private final Color color;

    private final IUser user;

    public Category(int id, IUser user, String title, Color color, ITask[] tasks) {
        super(tasks);
        this.id = id;
        this.user = user;
        this.title = title;
        this.color = color;
    }

    @Override
    public int getId() {
        return id;
    }

    @Override
    public IUser getUser() {
        return user;
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public Color getColor() {
        return color;
    }

    /* Generated by IDEA */

}
