package cz.ucl.logic.app.entities;

import cz.ucl.logic.app.entities.definition.*;

import java.util.Objects;

public class Tag extends TaskOwner implements ITag {

    private final int id;
    private final IUser user;
    private final String title;
    private final Color color;

    public Tag(int id, IUser user, String title, Color color, ITask[] tasks) {
        super(tasks);
        this.id = id;
        this.user = user;
        this.title = title;
        this.color = color;
    }

    @Override
    public int getId() {
        return 0;
    }

    @Override
    public IUser getUser() {
        return null;
    }

    @Override
    public String getTitle() {
        return null;
    }

    @Override
    public Color getColor() {
        return null;
    }

    /* Generated by IDEA */

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        Tag tag = (Tag) o;
        return id == tag.id &&
                Objects.equals(user, tag.user) &&
                Objects.equals(title, tag.title) &&
                color == tag.color;
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), id, user, title, color);
    }
}
