package cz.ucl.logic.app.entities;

import cz.ucl.logic.app.entities.definition.Color;
import cz.ucl.logic.app.entities.definition.ITag;
import cz.ucl.logic.app.entities.definition.ITask;
import cz.ucl.logic.app.entities.definition.IUser;

public final class Tag extends TaskOwner implements ITag {

    private final int id;
    private final String title;

    private final Color color;

    private final IUser user;

    public Tag(int id, IUser user, String title, Color color, ITask[] tasks) {
        super(tasks);
        this.id = id;
        this.user = user;
        this.title = title;
        this.color = color;
    }

    @Override
    public int getId() {
        return 0;
    }

    @Override
    public IUser getUser() {
        return null;
    }

    @Override
    public String getTitle() {
        return null;
    }

    @Override
    public Color getColor() {
        return null;
    }

    /* Generated by IDEA */

}
