package cz.ucl.logic.app.entities;

import cz.ucl.logic.app.entities.definition.Color;
import cz.ucl.logic.app.entities.definition.ITag;
import cz.ucl.logic.app.entities.definition.task.ITask;
import cz.ucl.logic.app.entities.definition.IUser;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Objects;

public final class Tag extends TaskOwner implements ITag {

    private final long id;

    @NotNull
    @Size(min = 1)
    private final String title;

    private final Color color;

    @NotNull
    private final IUser user;

    public Tag(long id, IUser user, String title, Color color, ITask[] tasks) {
        super(tasks);
        this.id = id;
        this.user = user;
        this.title = title;
        this.color = color;
    }

    @Override
    public long getId() {
        return id;
    }

    @Override
    public IUser getUser() {
        return user;
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public Color getColor() {
        return color;
    }

    /* Generated by IDEA */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        Tag tag = (Tag) o;
        return id == tag.id &&
                Objects.equals(title, tag.title) &&
                color == tag.color &&
                Objects.equals(user, tag.user);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), id, title, color, user);
    }
}
