package cz.ucl.logic.app.entities;

import cz.ucl.logic.app.entities.definition.Color;
import cz.ucl.logic.app.entities.definition.ICategory;
import cz.ucl.logic.app.entities.definition.ITask;
import cz.ucl.logic.app.entities.definition.IUser;

import java.util.Objects;

public class Category extends TaskOwner implements ICategory {

    private final int id;
    private final IUser user;
    private final String title;
    private final Color color;

    public Category(int id, IUser user, String title, Color color, ITask[] tasks) {
        super(tasks);
        this.id = id;
        this.user = user;
        this.title = title;
        this.color = color;
    }

    @Override
    public int getId() {
        return id;
    }

    @Override
    public IUser getUser() {
        return user;
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public Color getColor() {
        return color;
    }

    /* Generated by IDEA */

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        Category category = (Category) o;
        return id == category.id &&
                Objects.equals(user, category.user) &&
                Objects.equals(title, category.title) &&
                color == category.color;
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), id, user, title, color);
    }
}
